// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chatproto.proto

package chatproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// definition of struct used in Chat function
type ChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	mi := &file_chatproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chatproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_chatproto_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chatproto_proto protoreflect.FileDescriptor

const file_chatproto_proto_rawDesc = "" +
	"\n" +
	"\x0fchatproto.proto\x12\tchatproto\";\n" +
	"\aChatMsg\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2C\n" +
	"\vChatService\x124\n" +
	"\x04Chat\x12\x12.chatproto.ChatMsg\x1a\x12.chatproto.ChatMsg\"\x00(\x010\x01B\x14Z\x12grpcchat/chatprotob\x06proto3"

var (
	file_chatproto_proto_rawDescOnce sync.Once
	file_chatproto_proto_rawDescData []byte
)

func file_chatproto_proto_rawDescGZIP() []byte {
	file_chatproto_proto_rawDescOnce.Do(func() {
		file_chatproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatproto_proto_rawDesc), len(file_chatproto_proto_rawDesc)))
	})
	return file_chatproto_proto_rawDescData
}

var file_chatproto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chatproto_proto_goTypes = []any{
	(*ChatMsg)(nil), // 0: chatproto.ChatMsg
}
var file_chatproto_proto_depIdxs = []int32{
	0, // 0: chatproto.ChatService.Chat:input_type -> chatproto.ChatMsg
	0, // 1: chatproto.ChatService.Chat:output_type -> chatproto.ChatMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatproto_proto_init() }
func file_chatproto_proto_init() {
	if File_chatproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatproto_proto_rawDesc), len(file_chatproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatproto_proto_goTypes,
		DependencyIndexes: file_chatproto_proto_depIdxs,
		MessageInfos:      file_chatproto_proto_msgTypes,
	}.Build()
	File_chatproto_proto = out.File
	file_chatproto_proto_goTypes = nil
	file_chatproto_proto_depIdxs = nil
}
